### ISSUE TITLE
coinbase.verifyCallback complains (verify buffer)  -  TypeError: Not a string or buffer

### ISSUE THREAD

**Issue by aristidesfl** [expressjs/body-parser#153]
It seems the verifyCallback is not accepting the *buffer* provided by `verify`.

The code:
```
app.post('/coinbase/notifications', bodyParser.json({ verify: function(req, res, buf) {
  if (!coinbaseClient.verifyCallback(buf, req.headers['X-Signature'])) {
    throw new Error('Coinbase notification did not verify');
  }
}}));
```
The error:
```
TypeError: Not a string or buffer
  at TypeError (native)
  at Verify.verify (crypto.js:307:23)
  at Base.Client.verifyCallback (/Users/user/Work/express/node_modules/coinbase/lib/Client.js:250:19)
  at verifyCoinbaseNotification (/Users/user/Work/express/src/app.coffee:17:18)
  at /Users/user/Work/express/node_modules/body-parser/lib/read.js:100:9
  at invokeCallback (/Users/user/Work/express/node_modules/body-parser/node_modules/raw-body/index.js:262:16)
  at done (/Users/user/Work/express/node_modules/body-parser/node_modules/raw-body/index.js:251:7)
  at IncomingMessage.onEnd (/Users/user/Work/express/node_modules/body-parser/node_modules/raw-body/index.js:308:7)
  at emitNone (events.js:67:13)
  at IncomingMessage.emit (events.js:166:7)
  at endReadableNT (_stream_readable.js:905:12)
  at nextTickCallbackWith2Args (node.js:474:9)
  at process._tickCallback (node.js:388:17)
```

https://github.com/coinbase/coinbase-node/issues/51

**Comment by dougwilson** [comment]
Can you paste the result of doing `console.dir(buf)` and `console.dir(req.headers['X-Signature'])` ? Perhaps the header is `undefined`?

**Comment by dougwilson** [comment]
The reason I say that is because the stack trace show that the issue is with your second argument, the `signature` one.

**Comment by aristidesfl** [comment]
You are right, the problem is case sensitivity of the header key. But where in the stack trace do you see that it is the second argument?

**Comment by dougwilson** [comment]
> But where in the stack trace do you see that it is the second argument?

What gave it away was the line
```
  at Base.Client.verifyCallback (/Users/user/Work/express/node_modules/coinbase/lib/Client.js:250:19)
```
The only input into that method from your arguments is `signature` (https://github.com/coinbase/coinbase-node/blob/master/lib/Client.js#L250). If `body` were not a bufer/string, it would have thrown one line up from that.

**Comment by aristidesfl** [comment]
Thanks again!
