### ISSUE TITLE
Error: has no method 'parse'

### ISSUE THREAD

**Issue by miduga** [expressjs/body-parser#161]
I'm not able to get working body-parser as expected. Sometimes it's working, sometimes is not. It's a random problem that's happening a lot while I can't get a pattern about why is happening. :/

Code:
```coffeescript
  bodyParser    = require 'body-parser'
  # parse application/x-www-form-urlencoded
  urlencodedParser = bodyParser.urlencoded()
  app.post '/send-feedback', urlencodedParser, formsController.feedback
```

Error stack:
```
Object function bytes(value, options) {
 var bytesObj = new Bytes();

 if (typeof value === 'string') {
   return bytesObj.parse(value);
 }

 if (typeof value === 'number') {
   return bytesObj.convert(value, options);
 }

 return null;
} has no method 'parse'
TypeError: Object function bytes(value, options) {
 var bytesObj = new Bytes();

 if (typeof value === 'string') {
   return bytesObj.parse(value);
 }

 if (typeof value === 'number') {
   return bytesObj.convert(value, options);
 }

 return null;
} has no method 'parse'
 at getRawBody (/usr/hubii/news-site/node_modules/body-parser/node_modules/raw-body/index.js:97:21)
 at read (/usr/hubii/news-site/node_modules/body-parser/lib/read.js:76:3)
 at urlencodedParser (/usr/hubii/news-site/node_modules/body-parser/lib/types/urlencoded.js:109:5)
 at Layer.handle [as handle_request] (/usr/hubii/news-site/node_modules/express/lib/router/layer.js:95:5)
 at next (/usr/hubii/news-site/node_modules/express/lib/router/route.js:131:13)
 at Route.dispatch (/usr/hubii/news-site/node_modules/express/lib/router/route.js:112:3)
 at Layer.handle [as handle_request] (/usr/hubii/news-site/node_modules/express/lib/router/layer.js:95:5)
 at /usr/hubii/news-site/node_modules/express/lib/router/index.js:277:22
 at Function.process_params (/usr/hubii/news-site/node_modules/express/lib/router/index.js:330:12)
 at next (/usr/hubii/news-site/node_modules/express/lib/router/index.js:271:10)
 at checkCorrectLanguage (/usr/hubii/news-site/app.coffee:97:5)
 at Layer.handle [as handle_request] (/usr/hubii/news-site/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/usr/hubii/news-site/node_modules/express/lib/router/index.js:312:13)
 at /usr/hubii/news-site/node_modules/express/lib/router/index.js:280:7
 at Function.process_params (/usr/hubii/news-site/node_modules/express/lib/router/index.js:330:12)
 at next (/usr/hubii/news-site/node_modules/express/lib/router/index.js:271:10)
 at app.use.res.locals.acceptedCookies.ref5 (/usr/hubii/news-site/app.coffee:88:7)
 at Layer.handle [as handle_request] (/usr/hubii/news-site/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/usr/hubii/news-site/node_modules/express/lib/router/index.js:312:13)
 at /usr/hubii/news-site/node_modules/express/lib/router/index.js:280:7
 at Function.process_params (/usr/hubii/news-site/node_modules/express/lib/router/index.js:330:12)
 at next (/usr/hubii/news-site/node_modules/express/lib/router/index.js:271:10)
 at /usr/hubii/news-site/node_modules/i18next/lib/i18next.js:119:13
 at /usr/hubii/news-site/node_modules/i18next/node_modules/i18next-client/i18next.js:992:21
 at Object.i18n.functions.extend.load (/usr/hubii/news-site/node_modules/i18next/lib/i18nextWrapper.js:326:17)
 at init (/usr/hubii/news-site/node_modules/i18next/node_modules/i18next-client/i18next.js:988:19)
 at Object.setLng (/usr/hubii/news-site/node_modules/i18next/node_modules/i18next-client/i18next.js:1200:16)
 at i18n.handle (/usr/hubii/news-site/node_modules/i18next/lib/i18next.js:117:14)
 at Layer.handle [as handle_request] (/usr/hubii/news-site/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/usr/hubii/news-site/node_modules/express/lib/router/index.js:312:13)
 at /usr/hubii/news-site/node_modules/express/lib/router/index.js:280:7
 at Function.process_params (/usr/hubii/news-site/node_modules/express/lib/router/index.js:330:12)
 at next (/usr/hubii/news-site/node_modules/express/lib/router/index.js:271:10)
 at cookieParser (/usr/hubii/news-site/node_modules/cookie-parser/index.js:70:5)
 at Layer.handle [as handle_request] (/usr/hubii/news-site/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/usr/hubii/news-site/node_modules/express/lib/router/index.js:312:13)
 at /usr/hubii/news-site/node_modules/express/lib/router/index.js:280:7
 at Function.process_params (/usr/hubii/news-site/node_modules/express/lib/router/index.js:330:12)
 at next (/usr/hubii/news-site/node_modules/express/lib/router/index.js:271:10)
 at serveStatic (/usr/hubii/news-site/node_modules/express/node_modules/serve-static/index.js:74:16)
 at Layer.handle [as handle_request] (/usr/hubii/news-site/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/usr/hubii/news-site/node_modules/express/lib/router/index.js:312:13)
 at /usr/hubii/news-site/node_modules/express/lib/router/index.js:280:7
 at Function.process_params (/usr/hubii/news-site/node_modules/express/lib/router/index.js:330:12)
 at next (/usr/hubii/news-site/node_modules/express/lib/router/index.js:271:10)
 at favicon (/usr/hubii/news-site/node_modules/serve-favicon/index.js:72:7)
 at Layer.handle [as handle_request] (/usr/hubii/news-site/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/usr/hubii/news-site/node_modules/express/lib/router/index.js:312:13)
 at /usr/hubii/news-site/node_modules/express/lib/router/index.js:280:7
 at Function.process_params (/usr/hubii/news-site/node_modules/express/lib/router/index.js:330:12)
 at next (/usr/hubii/news-site/node_modules/express/lib/router/index.js:271:10)
 at compression (/usr/hubii/news-site/node_modules/compression/index.js:218:5)
 at Layer.handle [as handle_request] (/usr/hubii/news-site/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/usr/hubii/news-site/node_modules/express/lib/router/index.js:312:13)
 at /usr/hubii/news-site/node_modules/express/lib/router/index.js:280:7
 at Function.process_params (/usr/hubii/news-site/node_modules/express/lib/router/index.js:330:12)
 at next (/usr/hubii/news-site/node_modules/express/lib/router/index.js:271:10)
 at expressInit (/usr/hubii/news-site/node_modules/express/lib/middleware/init.js:33:5)
 at Layer.handle [as handle_request] (/usr/hubii/news-site/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/usr/hubii/news-site/node_modules/express/lib/router/index.js:312:13)
 at /usr/hubii/news-site/node_modules/express/lib/router/index.js:280:7
 at Function.process_params (/usr/hubii/news-site/node_modules/express/lib/router/index.js:330:12)
 at next (/usr/hubii/news-site/node_modules/express/lib/router/index.js:271:10)
 at query (/usr/hubii/news-site/node_modules/express/lib/middleware/query.js:49:5)
 at Layer.handle [as handle_request] (/usr/hubii/news-site/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/usr/hubii/news-site/node_modules/express/lib/router/index.js:312:13)
 at /usr/hubii/news-site/node_modules/express/lib/router/index.js:280:7
 at Function.process_params (/usr/hubii/news-site/node_modules/express/lib/router/index.js:330:12)
 at next (/usr/hubii/news-site/node_modules/express/lib/router/index.js:271:10)
 at Function.handle (/usr/hubii/news-site/node_modules/express/lib/router/index.js:176:3)
 at EventEmitter.handle (/usr/hubii/news-site/node_modules/express/lib/application.js:173:10)
 at Server.app (/usr/hubii/news-site/node_modules/express/lib/express.js:38:9)
 at Server.EventEmitter.emit (events.js:98:17)
 at HTTPParser.parser.onIncoming (http.js:2108:12)
 at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
 at Socket.socket.ondata (http.js:1966:22)
 at TCP.onread (net.js:525:27)
```

**Comment by dougwilson** [comment]
Can you provide the output from `npm ls > /dev/null`? Sounds like your install is in an invalid state w.r.t. the `bytes` module.

**Comment by dougwilson** [comment]
Easiest way to fix would be to re-form your entire `node_modules` tree, with the following commands:
```
$ rm -rf node_modules
$ npm cache clean
$ npm installl
```
