### ISSUE TITLE
Error: specified encoding unsupported

### ISSUE THREAD

**Issue by natevw** [expressjs/body-parser#178]
On a fresh install of dependencies for `"connect": "2.x"` under node v0.10.32, I am getting the following error when I submit an `application/x-www-form-urlencoded` form:

```
2016-06-13T16:37:00Z Error: specified encoding unsupported
2016-06-13T16:37:00Z     at makeError (myapp/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:184:15)
2016-06-13T16:37:00Z     at getDecoder (myapp/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:156:15)
2016-06-13T16:37:00Z     at module.exports (myapp/node_modules/connect/node_modules/body-parser/node_modules/raw-body/index.js:75:15)
2016-06-13T16:37:00Z     at read (myapp/node_modules/connect/node_modules/body-parser/lib/read.js:65:3)
2016-06-13T16:37:00Z     at urlencodedParser (myapp/node_modules/connect/node_modules/body-parser/lib/types/urlencoded.js:81:5)
2016-06-13T16:37:00Z     at myapp/node_modules/connect/lib/middleware/bodyParser.js:62:7
2016-06-13T16:37:00Z     at jsonParser (myapp/node_modules/connect/node_modules/body-parser/lib/types/json.js:71:36)
2016-06-13T16:37:00Z     at Object.bodyParser [as handle] (myapp/node_modules/connect/lib/middleware/bodyParser.js:60:5)
2016-06-13T16:37:00Z     at next (myapp/node_modules/connect/lib/proto.js:169:15)
```

This does not happen when testing a fresh install of the same package.json on my local dev machine, which is running node v6.2.0.

On both installs the `npm list` looks like this:

```
├─┬ connect@2.30.2
│ ├── basic-auth-connect@1.0.0
│ ├─┬ body-parser@1.13.3
│ │ ├── iconv-lite@0.4.11
│ │ ├─┬ on-finished@2.3.0
│ │ │ └── ee-first@1.1.1
│ │ └─┬ raw-body@2.1.6
│ │   ├── bytes@2.3.0
│ │   └── iconv-lite@0.4.13
…
```

**Comment by natevw** [comment]
Hrm, this may have just been a failure to restart my server process after updating the node dependencies. The problem seems to have gone away of its own accord even without upgrading off the old version of node [yet].

**Comment by dougwilson** [comment]
Hi @natevw, it looks like that dependency tree is installing a version of this module from about 1 year ago, so I don't think anything has changed (or that there is much we could do if that were the case). It's possible that the install was corrupted, or even I think `iconv-lite` does try to do a file system read, so a read failure can result in `iconv-lite` to report that it does not have a decoder available if the file system was altered underneath a running process.
