### ISSUE TITLE
UnsupportedMediaTypeError: unsupported charset "GBK"

### ISSUE THREAD

**Issue by cxh01987** [expressjs/body-parser#205]
When I use the this package for my app, I got the follow error:  
```
UnsupportedMediaTypeError: unsupported charset "GBK"
    at urlencodedParser (/mnt/vxdb/codes/blq-ali/node_modules/body-parser/lib/types/urlencoded.js:108:12)
    at Layer.handle [as handle_request] (/mnt/vxdb/codes/blq-ali/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/mnt/vxdb/codes/blq-ali/node_modules/express/lib/router/index.js:312:13)
    at /mnt/vxdb/codes/blq-ali/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/mnt/vxdb/codes/blq-ali/node_modules/express/lib/router/index.js:330:12)
    at next (/mnt/vxdb/codes/blq-ali/node_modules/express/lib/router/index.js:271:10)
    at jsonParser (/mnt/vxdb/codes/blq-ali/node_modules/body-parser/lib/types/json.js:112:7)
    at Layer.handle [as handle_request] (/mnt/vxdb/codes/blq-ali/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/mnt/vxdb/codes/blq-ali/node_modules/express/lib/router/index.js:312:13)
    at /mnt/vxdb/codes/blq-ali/node_modules/express/lib/router/index.js:280:7
```
My env like this:

Centos 7
node v4.2.1
Python 2.6.6
GCC 4.4.7 

request content like this:
```
REQUEST URL: http://mydomain/gateway.do
    REQUEST METHOD: POST
    CONTENT:
    service=alipay.service.check    sign=ntjOmXFGJMdfdMnrTL5rEp9QG8d0lDEoGg3ZHvqemHeI8BlQoEsFbhEn0IfQT+pvfJz5RCuE+3Qh1X7I4z5iTIiGjDBstc0xeuiAmtP9TrJZuw2jUAODFB9qOwBJLNcWlKHUGTU/db/qRsJQCj8EjoJvSi9MRM/xKv/XmduS/C4=
    sign_type=RSA
    charset=GBK
biz_content=<?xml version="1.0" encoding="gbk"?><XML><AppId><![CDATA[2014072300007148]]></AppId><FromUserId></FromUserId><CreateTime><![CDATA[1406083506817]]></CreateTime><MsgType><![CDATA[event]]></MsgType><EventType><![CDATA[verifygw]]></EventType><ActionParam></ActionParam><AgreementId></AgreementId><AccountNo></AccountNo></XML>
```

**Comment by dougwilson** [comment]
Currently the urlencoded parser only supports the body content encoded in UTF-8

**Comment by cxh01987** [comment]
could you set it to configurable?

**Comment by dougwilson** [comment]
Well, the support isn't something you can just switch; you need to actually go and decode it properly as well. If you want to put together a PR that would help :)

**Comment by dougwilson** [comment]
Closing since it doesn't seem like any PR has come forward to support the decoding.
