### ISSUE TITLE
can't send request with form-data

### ISSUE THREAD

**Issue by Selen34** [expressjs/body-parser#262]
When I use limit and send a png (~600kb) with form-data
`app.use(fileUpload())
app.use(bodyParser.json({ limit: '25mb' }))
app.use(bodyParser.urlencoded({ extended: true }))`
I got this:

> SyntaxError: Unexpected token -
    at parse (C:\Users\<My Project>\node_modules\body-parser\lib\types\json.js:83:15)
    at C:\Users\<My Project>\node_modules\body-parser\lib\read.js:116:18
    at invokeCallback (C:\Users\<My Project>\node_modules\raw-body\index.js:262:16)
    at done (C:\Users\<My Project>\node_modules\raw-body\index.js:251:7)
    at IncomingMessage.onEnd (C:\Users\<My Project>\node_modules\raw-body\index.js:307:7)
    at emitNone (events.js:105:13)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

When I use bodyParser without limit:
` app.use(bodyParser.json()) `

I got response 
> 413 Payload Too Large 

(For all requests I used postman, few day ago all was fine with sendind images)

**Comment by dougwilson** [comment]
Hi @Selen34 sorry to hear something broke for you in the past few days. Nothing has been published here in that time frame, so not sure what would have caused it. This module also doesn't support form-data, so not sure what is happening. I can take a look if you can provide the following:

1. Version of this module you're using.
2. An app that reproduces the issue.
3. The exact call and body content to submit to the app to trigger the issue.

**Comment by Selen34** [comment]
I found an unfortunate mistake. When sending via postman, it was necessary to remove the checkbox with the content-type :((
