### ISSUE TITLE
PayloadTooLargeError: too many parameters

### ISSUE THREAD

**Issue by jaman99** [expressjs/body-parser#305]
PayloadTooLargeError: too many parameters
    at queryparse (C:\Users\MD Jaman\Desktop\mywebpro\node_modules\body-parser\lib\types\urlencoded.js:151:13)
    at parse (C:\Users\MD Jaman\Desktop\mywebpro\node_modules\body-parser\lib\types\urlencoded.js:75:9)
    at C:\Users\MD Jaman\Desktop\mywebpro\node_modules\body-parser\lib\read.js:121:18
    at invokeCallback (C:\Users\MD Jaman\Desktop\mywebpro\node_modules\raw-body\index.js:224:16)
    at done (C:\Users\MD Jaman\Desktop\mywebpro\node_modules\raw-body\index.js:213:7)
    at IncomingMessage.onEnd (C:\Users\MD Jaman\Desktop\mywebpro\node_modules\raw-body\index.js:273:7)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)

**Comment by dougwilson** [comment]
https://github.com/expressjs/body-parser/blob/master/README.md#too-many-parameters
