### ISSUE TITLE
backslash in json

### ISSUE THREAD

**Issue by lacivert** [expressjs/body-parser#353]
Request body is like this:

```
{
  "username": "admin",
  "password": "abc%\-xyz"
}
```

I cannot control the request body comes from the client and the passwords can have such characters like backslash. App always gives this error:

```
SyntaxError: Unexpected number in JSON at position 45
    at JSON.parse (<anonymous>)
    at parse (/path/to/project/node_modules/body-parser/lib/types/json.js:93:19)
    at /path/to/project/node_modules/body-parser/lib/read.js:121:18
    at invokeCallback (/path/to/project/node_modules/raw-body/index.js:224:16)
    at done (/path/to/project/node_modules/raw-body/index.js:213:7)
    at IncomingMessage.onEnd (/path/to/project/node_modules/raw-body/index.js:273:7)
    at IncomingMessage.emit (events.js:189:13)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

What do I need to do in this case? 

`bodyParser.json({strict: false})` doesn't help

**Comment by lacivert** [comment]
Sorry for the misunderstanding. I have asked this on stackoverflow and I see now what happens. The issue is not related to the parsing, it was about printing the parsed value on the server.

I saw the password value with two backslashes in the server still with two backslashes. It must be like console.log() with one string param instead of multiple params like objects.
