### ISSUE TITLE
TypeError: Cannot read property 'chat' of undefined

### ISSUE THREAD

**Issue by mskian** [expressjs/body-parser#356]
I got this Error on My Expressjs code which written for Telegram bot I Hosted this code on CloudVps with Nginx I used this for Telegram Bot API webhook

It is a Telegram chat bot set some auto-replies when user input Matches it will send the Autoreply.

## Error from Log file

```js
TypeError: Cannot read property 'chat' of undefined
    at app.post (/var/www/hellobot/index.js:22:37)
    at Layer.handle [as handle_request] (/var/www/hellobot/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/hellobot/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/var/www/hellobot/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/var/www/hellobot/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/hellobot/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/var/www/hellobot/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/hellobot/node_modules/express/lib/router/index.js:275:10)
    at /var/www/hellobot/node_modules/body-parser/lib/read.js:130:5
    at invokeCallback (/var/www/hellobot/node_modules/raw-body/index.js:224:16)
```

## Full Code

```js
const express = require('express');
const app = express();
const bodyParser = require('body-parser');
const axios = require('axios');

const port = 8080;
const url = 'https://api.telegram.org/bot';
const apiToken = '<token>';


app.use(bodyParser.json());
app.use(bodyParser.urlencoded({
    extended: true
}));

app.listen(port, () => {
    console.log(`Listening on port ${port}`);
});

app.post('/', (req, res, next) => {
    var Content = require('./blogposts.json');
    var random = Content.blogtext[Math.floor(Math.random() * Content.blogtext.length)];
    const chatId = req.body.message.chat.id;
    const sentMessage = req.body.message.text || req.body.message.sticker.file_id;
    if (sentMessage.match(/start/gi)) {
        axios.post(`${url}${apiToken}/sendMessage`, {
                chat_id: chatId,
                text: 'Hello I am Bot',
            })
            .then((response) => {
                next();
                res.status(200).send(response);
                return res.end();
            }).catch((error) => {
                res.send(error);
            });
    } else if (sentMessage.match(/posts/gi)) {
        axios.post(`${url}${apiToken}/sendMessage`, {
                chat_id: chatId,
                text: random.blogtext,
            })
            .then((response) => {
                next();
                res.status(200).send(response);
            }).catch((error) => {
                res.send(error);
            });
    } else {
        axios.post(`${url}${apiToken}/sendMessage`, {
                chat_id: chatId,
                text: 'Sorry answer not found',
            })
            .then((response) => {
                res.status(200).send(response);
            }).catch((error) => {
                res.send(error);
            });
    }
});
```

Also got this Below error too

```js
BadRequestError: request aborted
    at IncomingMessage.onAborted (/var/www/hellobott/node_modules/raw-body/index.js:231:10)
    at IncomingMessage.emit (events.js:189:13)
    at abortIncoming (_http_server.js:449:9)
    at socketOnClose (_http_server.js:442:3)
    at Socket.emit (events.js:194:15)
    at TCP._handle.close (net.js:597:12)
```

**Comment by dougwilson** [comment]
> TypeError: Cannot read property 'chat' of undefined

This is happening in your code, noting to do with this module. If you look at line 22, you're accessing `req.body.message.chat.id` and assuming that the request that came into your service had a message object, which it didn't in this case.

You'll need to account for that however you see fit.

> BadRequestError: request aborted

https://github.com/expressjs/body-parser#request-aborted
