### ISSUE TITLE
Unexpected token " in JSON at position 0

### ISSUE THREAD

**Issue by sundaram2021** [expressjs/body-parser#488]
`SyntaxError: Unexpected token " in JSON at position 0
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (C:\Desktop\FullStack\mern-stack\server\node_modules\body-parser\lib\types\json.js:160:10)
    at parse (C:\Desktop\FullStack\mern-stack\server\node_modules\body-parser\lib\types\json.js:83:15)
    at C:\Desktop\FullStack\mern-stack\server\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (C:\Desktop\FullStack\mern-stack\server\node_modules\raw-body\index.js:231:16)
    at done (C:\Desktop\FullStack\mern-stack\server\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (C:\Desktop\FullStack\mern-stack\server\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1358:12)
`

I am getting this error while sending data to the server in express

**Comment by dougwilson** [comment]
If you are trying to send a plain string, you need to set `strict: false` on your json parser: https://github.com/expressjs/body-parser#strict

**Comment by sundaram2021** [comment]
Hey , Thanks for advice 

But , the error was in front end side wherein i am not sending 
this,
```
const [work, setWork] = useState({
    todo: "",
  });
```
instead 

`const [work, setWork] = useState();`

But it resolves at the end
