### ISSUE TITLE
"RangeError: Maximum call stack size exceeded" (urlencode) / "SyntaxError: Unexpected token" (json)

### ISSUE THREAD

**Issue by q2dg** [expressjs/body-parser#77]
Hello.
I have this code:
```js
var express = require("express")
var bp = require("body-parser")
var app = express()
var bpurle= app.use(bp.urlencoded({ extended: false }))
var bpjson= app.use(bp.json())
app.post("/urle", bpurle, function(req, res) {
    if (req.body === undefined) {return(console.log("There aren't any data"))}
    console.log("Received data via URL-Encode:\n" + req.body)
})
app.post("/json", bpjson, function(req, res) {
    if (req.body === undefined) {return(console.log("There aren't any data"))}
    console.log("Received data via JSON:\n" + JSON.stringify(req.body,null,2))
})
app.listen(4000)
```
When I execute... 

```sh
curl -X POST http://127.0.0.1:4000/urle -d "data1=value1&data2=1234"
```
...I get this error:
```
RangeError: Maximum call stack size exceeded
    at next (/home/q2dg/node_modules/express/lib/router/index.js:168:16)
    at next (/home/q2dg/node_modules/express/lib/router/route.js:100:14)
    at Layer.handle_error (/home/q2dg/node_modules/express/lib/router/layer.js:54:12)
    at next (/home/q2dg/node_modules/express/lib/router/route.js:108:13)
    at /home/q2dg/node_modules/express/lib/router/index.js:603:15
    at next (/home/q2dg/node_modules/express/lib/router/index.js:246:14)
    at next (/home/q2dg/node_modules/express/lib/router/route.js:100:14)
    at Layer.handle_error (/home/q2dg/node_modules/express/lib/router/layer.js:54:12)
    at next (/home/q2dg/node_modules/express/lib/router/route.js:108:13)
    at /home/q2dg/node_modules/express/lib/router/index.js:603:15
```
When I execute...
```sh
curl -X POST http://127.0.0.1:4000/json -d "{'data1':'value1','data2':'1234'}" -H "Content-Type:application/json"
```
...I get this error:
```
SyntaxError: Unexpected token '
    at Object.parse (native)
    at parse (/home/q2dg/node_modules/body-parser/lib/types/json.js:76:17)
    at /home/q2dg/node_modules/body-parser/lib/read.js:98:18
    at IncomingMessage.onEnd (/home/q2dg/node_modules/body-parser/node_modules/raw-body/index.js:136:7)
    at IncomingMessage.g (events.js:199:16)
    at IncomingMessage.emit (events.js:104:17)
    at _stream_readable.js:907:16
    at process._tickCallback (node.js:372:11)
```
Thanks!

**Comment by dougwilson** [comment]
Hi! So, really, there are two different questions here. Regarding the second error from JSON.parse, the reason you get the error is because the `'` is not valid JSON; you can only use double quotes. This is just how the JSON format is defined, and nothing from this module.

For the first error, I''m not sure what is going on. What is the version of Express you are using?

**Comment by q2dg** [comment]
Thanks. 
Last stable: 4.11

**Comment by q2dg** [comment]
Well...if I correct my JSON mistake and I do...

**curl -X POST http://127.0.0.1:4000/json -d '{"data1":"value1","data2":"1234"}' -H "Content-Type:application/json"**

(namely, inverting simple and double quotes), I get the same error than with url-encode format:

*RangeError: Maximum call stack size exceeded
    at global.setImmediate (node.js:198:29)
    at next (/home/q2dg/node_modules/express/lib/router/index.js:188:7)
    at Layer.handle [as handle_request] (/home/q2dg/node_modules/express/lib/router/layer.js:84:5)
    at trim_prefix (/home/q2dg/node_modules/express/lib/router/index.js:302:13)
    at /home/q2dg/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/home/q2dg/node_modules/express/lib/router/index.js:321:12)
    at next (/home/q2dg/node_modules/express/lib/router/index.js:261:10)
    at expressInit (/home/q2dg/node_modules/express/lib/middleware/init.js:23:5)
    at Layer.handle [as handle_request] (/home/q2dg/node_modules/express/lib/router/layer.js:82:5)
    at trim_prefix (/home/q2dg/node_modules/express/lib/router/index.js:302:13)*

I've also noticed if I repeat curl command, the error message is similar but line numbers is not (I don't know if it is relevant):

*RangeError: Maximum call stack size exceeded
    at trim_prefix (/home/q2dg/node_modules/express/lib/router/index.js:297:5)
    at /home/q2dg/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/home/q2dg/node_modules/express/lib/router/index.js:321:12)
    at next (/home/q2dg/node_modules/express/lib/router/index.js:261:10)
    at Layer.handle_error (/home/q2dg/node_modules/express/lib/router/layer.js:54:12)
    at trim_prefix (/home/q2dg/node_modules/express/lib/router/index.js:300:13)
    at /home/q2dg/node_modules/express/lib/router/index.js:270:7
    at Function.proto.process_params (/home/q2dg/node_modules/express/lib/router/index.js:321:12)
    at next (/home/q2dg/node_modules/express/lib/router/index.js:261:10)
    at Layer.handle [as handle_request] (/home/q2dg/node_modules/express/lib/router/layer.js:84:5)*

Thanks a lot for your patience

**Comment by dougwilson** [comment]
And you are sure that the code at the top is the _only_ code for the entire server you are getting the `RangeError` on?

**Comment by q2dg** [comment]
Yes, totally

**Comment by dougwilson** [comment]
Ok, I see. you created a circular dependency. You just need to remove the two `app.use()` statements to make your server look like this:
```js
var express = require("express")
var bp = require("body-parser")
var app = express()
var bpurle= bp.urlencoded({ extended: false })
var bpjson= bp.json()
app.post("/urle", bpurle, function(req, res) {
    if (req.body === undefined) {return(console.log("There aren't any data"))}
    console.log("Received data via URL-Encode:\n" + req.body)
})
app.post("/json", bpjson, function(req, res) {
    if (req.body === undefined) {return(console.log("There aren't any data"))}
    console.log("Received data via JSON:\n" + JSON.stringify(req.body,null,2))
})
app.listen(4000)
```

**Comment by q2dg** [comment]
Ooooh, so sorry!!
I though all Express middleware had to be inside app.use() to work (like serve-static, serve-index and so on) but it's not the case. Now I understand why: because i'm using it inside routing.
Thanks a lot again!!

**Comment by dougwilson** [comment]
It's no problem, I didn't even notice it at first, which is why I wanted to confirm that was your server's code before I ran it myself to figure it out :)
