### ISSUE TITLE
1.12.3 request aborted

### ISSUE THREAD

**Issue by PuKoren** [expressjs/body-parser#93]
With latest version some requests are aborted, there is the stack trace:

```js
Error: request aborted
    at makeError (/var/app/current/node_modules/body-parser/node_modules/raw-body/index.js:198:15)
    at IncomingMessage.onAborted (/var/app/current/node_modules/body-parser/node_modules/raw-body/index.js:103:15)
    at IncomingMessage.emit (events.js:104:17)
    at IncomingMessage.wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at IncomingMessage.wrappedEmit [as emit] (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:189:46)
    at abortIncoming (_http_server.js:279:11)
    at Socket.socketOnEnd (_http_server.js:393:7)
    at Socket.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at /var/app/current/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at wrapped (/var/app/current/node_modules/newrelic/lib/transaction/tracer/index.js:157:28)
    at _tickDomainCallback (node.js:381:11)
    at process.nextTickWrapper [as _tickCallback] (/var/app/current/node_modules/newrelic/lib/instrumentation/core/timers.js:18:14)
```

Sorry for newrelic trash in here, this is production log. Everything is fine with 1.12.2

**Comment by dougwilson** [comment]
This is correct, because with 1.12.2, those requests would actually _hang_, which was a huge bug! We now forward the error correctly.

**Comment by dougwilson** [comment]
Basically, the error is that the client, while uploading the body, disconnected before the entire body was received.

**Comment by PuKoren** [comment]
Ok thanks for your quick and clear answer!

**Comment by dougwilson** [comment]
No problem! One Thing that may help is that typically if we forward an error and have a HTTP status code that we think should go to the client, we set the `status` property on the error `err.status`. If you have the flexibility in your error reporting stuff, you could either ignore `err.status < 500` as it's a client error, or turn them into warnings or something :)

I know on my sites I typically ignore any errors that don't cause a status of >= 500 in my main error alerting system :)
