### ISSUE TITLE
Lib compat inside depd throw an error on requiring body-parser

### ISSUE THREAD

**Issue by martin-mh** [expressjs/body-parser#97]
Hi ! On starting the app, it immediatly freeze with this error message :

    /home/imote/Development/ushare-server/server/node_modules/bodyparser/node_modules/depd/lib/compat/index.js:28

    Error.captureStackTrace(obj)
          ^
    TypeError: undefined is not a function
      at callSiteToString (/home/imote/Development/ushare-server/server/node_modules/body-   parser/node_modules/depd/lib/compat/index.js:28:9)
    at Object.get [as callSiteToString] (/home/imote/Development/ushare-server/server/node_modules/body-parser/node_modules/depd/lib/compat/index.js:45:15)
    at Object.<anonymous> (/home/imote/Development/ushare-server/server/node_modules/body-parser/node_modules/depd/index.js:11:47)
    at Module._compile (module.js:428:26)
    at Object.Module._extensions..js (module.js:446:10)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (/home/imote/Development/ushare-server/server/node_modules/body-parser/index.js:11:17)

Just this line make it freeze in my app :

    var bodyParser = require('body-parser');

What do i need to do ? Thanks :)

**Comment by dougwilson** [comment]
Hmm. I believe this should have been fixed. What version of this module are you using and what version of Node.js?

**Comment by martin-mh** [comment]
I'm using the last version of body-parser (`1.12.3`). According to the *package.json* file inside body-parser, body-parser is using the version `~1.0.1` of depd.

I'm usually using io.js (the last version so `1.8.1`) but the bug is even here with the last node.js (`0.12.2`) and with node.js `v0.11.16`.

**Comment by dougwilson** [comment]
Interesting some of those versions have no issue on Travis CI and I just tried them myself with no issue. Is the only thing in your file the single require? Does the following work"

    iojs -ep 'require("body-parser")

It's possible you are loading some other module that is doing bad things if the above command works fine.

**Comment by martin-mh** [comment]
Oh yes you make it understanding !! I do not know why i do not understand this early when i take a look into this code.
I've this : 

    Error = function(string)
    {
	console.log(clc.red(string));
    };

And deps is using Error too. So it's making problems. Thanks to help me !!

**Comment by dougwilson** [comment]
Ah, yes, that would do it. Replacing `Error` is probably not a good idea. Think if you replaced `Object`, you would loose `Object.keys()` or if you replaced `Math`, you'd loose `Math.round()`.
